### ISSUE TITLE
while define subclass of websocket-client, how does `(name :initarg :user-agent)` work?

### ISSUE THREAD

**Issue by muyinliu** [capitaomorte/hunchensocket#11]
While define subclass of websocket-client, for example:
```lisp
(defclass client (hunchensocket:websocket-client)
  ((name :initarg :user-agent :initform (error "Name this client!") :accessor name)))
```
how does `(name :initarg :user-agent)` work? And can `:user-agent` be replaced by other things?

**Comment by capitaomorte** [comment]
They way it works, if I remember correctly when I designed this, is that you can set the `client-class` slot of your websocket resources. The client is made automatically by the hunchensocket engine and the class that you set there is instanced with the internal slots of `websocket-client` + headers that arrive in the request. So if `:user-agent` is a header in the resource as set by hunchensocket (or actually hunchentoot), it is used to initialize your instance.  And then you can use the `name` accessor to get to it.

In the particular case of `:user-agent` I think it is, i.e., all HTTP requests as seen by hunchentoot have that header.

If you change the initarg to something else like `:my-crazy-header` it will only get set if the request has that header, and will error out otherwise.

I think what you're trying to do is a reasonable way of using hunchensocket, but all this I'm just reading from the code I wrote more than one year ago...

**Comment by capitaomorte** [comment]
I just remembered that, in answering your specific question, you don't have to have a `:user-agent` initarg in your subclass. In the good spirit of CLOS, you can probably

```lisp
(defmethod initialize-instance :after ((c client) &rest args &key request user-agent &allow-other-keys)
  ;; do whatever you want with USER-AGENT, REQUEST, ARGS and C
)
```

**Comment by muyinliu** [comment]
That's what I want! Thanks!

**Comment by muyinliu** [comment]
Now I know the trick.
```lisp
(defmacro with-new-client-for-resource ((client-sym &key input-stream
                                                      output-stream
                                                      resource
                                                      request)
                                        &body body)
  (alexandria:once-only (resource request)
    `(let ((,client-sym (apply #'make-instance
                               (slot-value ,resource 'client-class)
                               'input-stream ,input-stream
                               'output-stream ,output-stream
                               'request ,request
                               :request ,request
                               (loop for (header . value)
                                       in (headers-in ,request)
                                     collect header collect value))))
       (call-with-new-client-for-resource ,client-sym
                                          ,resource
                                          #'(lambda () ,@body)))))
```
While calling `(make-instance 'client xxxxx)`, pass a lot of values by 
```lisp
(loop for (header . value)
          in (headers-in ,request)
     collect header collect value)
```
and `:user-agent` is one of them. So the value of slot `name` will set to the user-agent come from request.

Thanks again!

**Comment by capitaomorte** [comment]
> and :user-agent is one of them. 

*if* it's in the request headers :-)
